In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3])

In [4]:
a #comma seperated is list  space seperated is an array

array([1, 2, 3])

In [5]:
a=np.array([[1,2,3],[4,5,6]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(a)

numpy.ndarray

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a[0][2]

np.int64(3)

In [38]:
str=b"lavanya lakshmi"
np.frombuffer(str,dtype='S1')

array([b'l', b'a', b'v', b'a', b'n', b'y', b'a', b' ', b'l', b'a', b'k',
       b's', b'h', b'm', b'i'], dtype='|S1')

In [11]:
np.frombuffer(str,dtype='S1',count=5,offset=10)

array([b'k', b's', b'h', b'm', b'i'], dtype='|S1')

In [12]:
a=np.array([10,])

In [13]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [15]:
import numpy as np

In [16]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a=np.zeros([2,3,4])

In [18]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
np.zeros([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
import numpy as np

In [31]:
a=np.full([2,3,2],2)

In [26]:
a

array([[2, 2, 2],
       [2, 2, 2]])

In [34]:
np.random.rand(3,10)

array([[0.58770407, 0.29665382, 0.64085716, 0.40212644, 0.45708233,
        0.9828241 , 0.26798126, 0.49045273, 0.36183009, 0.77745742],
       [0.12819829, 0.19190284, 0.55944946, 0.92241188, 0.69270573,
        0.40039984, 0.64334274, 0.66267167, 0.96284909, 0.36499741],
       [0.39656053, 0.61067988, 0.46110211, 0.12576681, 0.22054887,
        0.16308525, 0.45450096, 0.77389876, 0.17766592, 0.63499978]])

In [35]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.arange(10,100,5,dtype=float)

array([10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65., 70.,
       75., 80., 85., 90., 95.])

In [51]:
a=np.arange(10,100,10)

In [53]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
a.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [56]:
a.reshape(1,9)

array([[10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [57]:
a.reshape(9,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [60]:
np.linspace(10,100,dtype=int)

array([ 10,  11,  13,  15,  17,  19,  21,  22,  24,  26,  28,  30,  32,
        33,  35,  37,  39,  41,  43,  44,  46,  48,  50,  52,  54,  55,
        57,  59,  61,  63,  65,  66,  68,  70,  72,  74,  76,  77,  79,
        81,  83,  85,  87,  88,  90,  92,  94,  96,  98, 100])

In [61]:
np.linspace(10,100,10,dtype=int,endpoint=False,retstep=True)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), np.float64(9.0))

In [67]:
np.logspace(0,10,10,dtype=int,base=2)

array([   1,    2,    4,   10,   21,   47,  101,  219,  474, 1024])

In [68]:
np.logspace(1,10,3)

array([1.00000000e+01, 3.16227766e+05, 1.00000000e+10])

In [69]:
                 # array properties
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
type(a)

numpy.ndarray

In [74]:
np.shape(a)
np.size(a)

9

In [75]:
          # array operations
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [76]:
a[0][1]

np.int64(20)

In [77]:
a[1]

array([40, 50, 60])

In [78]:
a[2][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [79]:
a[2][2]

np.int64(90)

In [83]:
a[0:2]# gives 0th & 1st index as o/p (end =2 nd index is excluded)

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
b=np.copy(a)

In [85]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [86]:
b is a

False

In [87]:
b.view()

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [93]:
print('a=',a )
print('b=',b)

a= [[10 20 30]
 [40 50 60]
 [70 80 90]]
b= [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [94]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [95]:
a[1][2]=500

In [96]:
a

array([[ 10,  20,  30],
       [ 40,  50, 500],
       [ 70,  80,  90]])

In [97]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [100]:
c=a.view()
a

array([[ 10,  20,  30],
       [ 40,  50, 500],
       [ 70,  80,  90]])

In [102]:
a[2][1]=800

In [103]:
a

array([[ 10,  20,  30],
       [ 40,  50, 500],
       [ 70, 800,  90]])

In [105]:
c # since c is the view (reference) of a,any changes in a refletcs in c

array([[ 10,  20,  30],
       [ 40,  50, 500],
       [ 70, 800,  90]])

In [1]:
import numpy as np

In [3]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [4]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
b=a.view()

In [10]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
a[1][1]=500

In [12]:
a

array([[ 10,  20,  30],
       [ 40, 500,  60],
       [ 70,  80,  90]])

In [13]:
b

array([[ 10,  20,  30],
       [ 40, 500,  60],
       [ 70,  80,  90]])

In [15]:
a[:]

array([[ 10,  20,  30],
       [ 40, 500,  60],
       [ 70,  80,  90]])

In [16]:
b[1][1]=50

In [17]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
a

array([[ 10,  20,  30],
       [ 40, 500,  60],
       [ 70,  80,  90]])

In [24]:
a.reshape(3,3)
a

array([[ 10,  20,  30],
       [ 40, 500,  60],
       [ 70,  80,  90]])

In [19]:
a[1:-1]

array([[ 40, 500,  60]])

In [20]:
x=np.array([10,20,30,40,50,60,70,80,90])
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
x[1:-1]

array([20, 30, 40, 50, 60, 70, 80])

In [22]:
np.sort(x)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
x=np.array([20,0,30,40,70,50,80,10,90])
x

array([20,  0, 30, 40, 70, 50, 80, 10, 90])

In [27]:
np.sort(x)

array([ 0, 10, 20, 30, 40, 50, 70, 80, 90])

In [28]:
y=np.array([[3,2,5],[9,1,4],[8,6,7]])
y

array([[3, 2, 5],
       [9, 1, 4],
       [8, 6, 7]])

In [35]:
np.sort(y,axis=0)# column wise sort in multi dimension array

array([[3, 1, 4],
       [8, 2, 5],
       [9, 6, 7]])

In [36]:
np.sort(y,axis=1)#row wise sort in multi dimension array(default)

array([[2, 3, 5],
       [1, 4, 9],
       [6, 7, 8]])

In [58]:
y.sort(axis=0)# column wise sort
y

array([[1, 3, 5],
       [2, 4, 8],
       [6, 7, 9]])

In [1]:
import numpy as np

In [2]:
y=np.array([[3,2,5],[9,1,4],[8,6,7]])

In [3]:
y

array([[3, 2, 5],
       [9, 1, 4],
       [8, 6, 7]])

In [4]:
x=np.array([[10,20,30],[40,50,60],[70,80,90]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
np.append(x,y). # append is 1-D

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[ 3,  2,  5],
        [ 9,  1,  4],
        [ 8,  6,  7]]])

In [8]:
np.append(x,y).reshape(2,3,3) 

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[ 3,  2,  5],
        [ 9,  1,  4],
        [ 8,  6,  7]]])

In [9]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
x=np.insert(x,2,[1,2]) # gives o/p in 1-D
# x---> appending array
# 2---> adding values at index 2 nd position values [1,2]

In [17]:
x

array([10, 20,  1,  2, 30, 40, 50, 60, 70, 80, 90])

In [21]:
x[2],x[3],x[4]

(np.int64(1), np.int64(2), np.int64(30))

In [22]:
x

array([10, 20,  1,  2, 30, 40, 50, 60, 70, 80, 90])

In [30]:
np.delete(x,0) # deletes element at 0th position


array([20,  1,  2, 30, 40, 50, 60, 70, 80, 90])

In [29]:
x

array([10, 20,  1,  2, 30, 40, 50, 60, 70, 80, 90])

In [40]:
x=np.insert(x,0,11)

In [41]:
x

array([11, 10, 20,  1,  2, 30, 40, 50, 60, 70, 80, 90])

In [42]:
x.reshape(3,4)

array([[11, 10, 20,  1],
       [ 2, 30, 40, 50],
       [60, 70, 80, 90]])

In [43]:
np.delete(x,x[0][3]) #  can't delete an element in mutli -d

IndexError: invalid index to scalar variable.

In [55]:
a=np.array([[1,2,3],[10,20,30]])
b=np.array([[4,5,6],[50,60,70]])
c=np.concatenate((a,b),axis=1)
# axis =1 --> row
#axis=0 ---> column
c

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 50, 60, 70]])

In [54]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concat((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [70]:
a=np.array([[1,2,3],[10,20,30]])
b=np.array([[4,5,6],[40,50,60]])
c=np.stack((a,b),axis=0)
c
#  stack makes 'a' array as one index i.e. 0
# and 'b' array as one index i.e. 1
# both arrays doesn't merge as one  whole array in satck at axis =0

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [40, 50, 60]]])

In [72]:
np.vstack((a,b)) # gives as o/p as one array 

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [40, 50, 60]])

In [73]:
np.hstack((a,b)) # gies o/p ast axis=1 

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [74]:
a,b

(array([[ 1,  2,  3],
        [10, 20, 30]]),
 array([[ 4,  5,  6],
        [40, 50, 60]]))

In [75]:
np.dstack((a,b))

array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[10, 40],
        [20, 50],
        [30, 60]]])

In [66]:
c[0]  ,c[1]

(array([[ 1,  2,  3],
        [10, 20, 30]]),
 array([[ 4,  5,  6],
        [40, 50, 60]]))

In [78]:
a=np.arange(10,100,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [79]:
import numpy as np

In [80]:
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [84]:
np.size(a)


18

In [94]:
b=a.reshape(2,3,3)

In [95]:
np.shape(b)

(2, 3, 3)

In [102]:
#splits array 'a' into 3 sepearte different arrays of equal size(length)


In [109]:
c=np.split(a,9) 
c

[array([10, 15]),
 array([20, 25]),
 array([30, 35]),
 array([40, 45]),
 array([50, 55]),
 array([60, 65]),
 array([70, 75]),
 array([80, 85]),
 array([90, 95])]

In [204]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
x=np.array_split(a,5) # we can split array into uneven parts also using 'array_split'

In [120]:
x

[array([1]),
 array([2]),
 array([3]),
 array([], dtype=int64),
 array([], dtype=int64)]

In [123]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[3,3,7]]) #checks 2 arrays are in sa length ,size,dtype
np.array_equal(a,b)

False

In [140]:
b.flatten() #converting mutli-D  to 1-D 

array([1, 3, 2, 3, 3, 7])

In [132]:
b is a

False

In [137]:
b=np.transpose(b) # transposing rows to col and col to rows
b

array([[1, 3],
       [2, 3],
       [3, 7]])

In [131]:
a=np.resize(b,2) #specifying only 2 elements need to be in array 'b'
a

array([1, 2])

In [125]:
a-b

array([[ 0,  0,  0],
       [-2, -1, -4]])

In [126]:
a**3

array([ 1,  8, 27])

In [127]:
a/2


array([0.5, 1. , 1.5])

In [124]:
np.max(b)

np.int64(7)

In [141]:
b

array([[1, 3],
       [2, 3],
       [3, 7]])

In [142]:
b>5

array([[False, False],
       [False, False],
       [False,  True]])

In [148]:
b=np.array([[[1,2,3],[10,20,30],[4,5,6],[40,50,60],[7,8,9],[70,80,90]]])
b

array([[[ 1,  2,  3],
        [10, 20, 30],
        [ 4,  5,  6],
        [40, 50, 60],
        [ 7,  8,  9],
        [70, 80, 90]]])

In [157]:
b.dtype

dtype('int64')

In [159]:
np.logical_and(b>3,b>3)

array([[[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [160]:
np.logical_not(b>100,b>50) # gives boolean values as o/p if the condition is satisfied

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [164]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])



In [166]:
c=np.matmul(a,b)
c

np.int64(550)

In [162]:
np.dot(a,b) # can be mostly  used for multi -d matrix multiplication

np.int64(550)

In [176]:
np.random.randn(2,2) # gets random no's with distribution differ


array([[-0.97466142,  0.78127034],
       [-1.33962792, -0.14210635]])

In [200]:
import numpy as np

In [206]:
b=np.array([[1,2,3],[10,20,30],[4,5,6],[40,50,60],[7,8,9],[70,80,90]])
b

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [40, 50, 60],
       [ 7,  8,  9],
       [70, 80, 90]])

In [222]:
np.shape(b)

(6, 3)

In [212]:
x=np.array_split(b,7)
x

[array([[1, 2, 3]]),
 array([[10, 20, 30]]),
 array([[4, 5, 6]]),
 array([[40, 50, 60]]),
 array([[7, 8, 9]]),
 array([[70, 80, 90]]),
 array([], shape=(0, 3), dtype=int64)]

In [221]:
x=np.array_split(b,5)
x

[array([[ 1,  2,  3],
        [10, 20, 30]]),
 array([[4, 5, 6]]),
 array([[40, 50, 60]]),
 array([[7, 8, 9]]),
 array([[70, 80, 90]])]

In [219]:
x=np.array_split(b,(5,4))
x

[array([[ 1,  2,  3],
        [10, 20, 30],
        [ 4,  5,  6],
        [40, 50, 60],
        [ 7,  8,  9]]),
 array([], shape=(0, 3), dtype=int64),
 array([[ 7,  8,  9],
        [70, 80, 90]])]

In [217]:
x,y,z,zx=np.array_split(b,4)
x,y,z,zx

(array([[ 1,  2,  3],
        [10, 20, 30]]),
 array([[ 4,  5,  6],
        [40, 50, 60]]),
 array([[7, 8, 9]]),
 array([[70, 80, 90]]))

In [223]:
b

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [40, 50, 60],
       [ 7,  8,  9],
       [70, 80, 90]])

In [224]:
np.where(b==100) # to find an element  index in an array

(array([], dtype=int64), array([], dtype=int64))

In [225]:
np.where(b==90)

(array([5]), array([2]))

In [227]:
np.where(b-2==0)

(array([0]), array([1]))

In [228]:
np.where(b%2==0)

(array([0, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5]),
 array([1, 0, 1, 2, 0, 2, 0, 1, 2, 1, 0, 1, 2]))

In [237]:
c=np.sort(b,axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [244]:
a=np.array([2,5,1,4,3])
a

array([2, 5, 1, 4, 3])

In [246]:
a.sort()
a

array([1, 2, 3, 4, 5])

In [247]:
np.searchsorted(a,4) # worrks as where ( gives index position of an element in sorted array of 1-D)

np.int64(3)

In [248]:
np.searchsorted(a,(3,4)) # binarysearch

array([2, 3])

In [249]:
a

array([1, 2, 3, 4, 5])

In [253]:
b=np.array([10,20,30,40,50])
b

array([10, 20, 30, 40, 50])

In [254]:
np.add(a,b)

array([11, 22, 33, 44, 55])

In [257]:
np.subtract(a,b)

array([ -9, -18, -27, -36, -45])

In [258]:
np.multiply(b,a)

array([ 10,  40,  90, 160, 250])

In [259]:
np.divide(a,b)

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [261]:
np.sqrt(b)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [264]:
b[1]==a[1]

np.False_

In [266]:
np.shape(a)

(5,)

In [265]:
np.array_equal(a,b) #array comparision

False

In [268]:
a==b #element wise comparision

array([False, False, False, False, False])

In [269]:
np.std(b)

np.float64(14.142135623730951)

In [270]:
np.sum(a)

np.int64(15)

In [271]:
np.max(a)

np.int64(5)

In [273]:
np.mean(a)

np.float64(3.0)

In [274]:
np.avg(a)

AttributeError: module 'numpy' has no attribute 'avg'

In [275]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [277]:
np.min(a,axis=1) # minimum value row wsie

array([1, 4, 7])

In [278]:
np.min(a,axis=0) #min value col wise

array([1, 2, 3])

In [279]:
np.sum(a,axis=0) # col wise sum

array([12, 15, 18])

In [280]:
np.median(a)

np.float64(5.0)

In [281]:
np.median(a,axis=1)

array([2., 5., 8.])

In [282]:
np.var(a,axis=0) # variance col wsie

array([6., 6., 6.])

In [283]:
np.std(a,axis=1)# standard deviation - col wise

array([0.81649658, 0.81649658, 0.81649658])

In [285]:
a=np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [286]:
np.linalg.inv(a) # matrix inversion  in linearalgebra funtion 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [287]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [ ]:
# np.save('filename.npy') --> save a file
# np.load('filename.npy') -->load a file
# np.savetxt('filename.txt',array) --> saving array to tex file
# np.loadtxt('filename') --> loads the array from that text file.
